name: Publish npm package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # 使用する Node.js のバージョン
          registry-url: https://registry.npmjs.org/
      - run: npm ci # または npm install
      - run: npm version patch # または npm version minor, npm version major
      - run: git config --global user.email "1127424+jhelom@users.noreply.github.com "
      - run: git config --global user.name "jhelom"
      - run: git commit -am "Bump version"
      - run: git push
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.currentVersion }}
          release_name: Release v${{ steps.package-version.outputs.currentVersion }}
          draft: false
          prerelease: false
