name: Publish to npm

on:
  push:
    branches:
      - main  # mainブランチが更新されたときに実行

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js 環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # 3. npm 依存関係をインストール
      - name: Install dependencies
        run: npm install

      # 4. バージョンを自動で上げる（patchを例に）
      - name: Bump version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A  # 変更をステージング
          git commit -m "Prepare for version bump [skip ci]" || echo "No changes to commit"
          npm version patch -m "Bump version to %s [skip ci]"
          git push origin main --follow-tags

      # 5. npm にパッケージを公開
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
